name: test deploy manual trigger workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
    
jobs:
  envirnment_demo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    # - uses: actions/checkout@v4
    - name: print environment variables of ${{ vars.ENVIRONMENT_NAME }} environment
      run: |
          echo ${{ vars.ENVIRONMENT_NAME }}
          echo ${{ vars.DOCKER_FILE_PATH }}

  # call-reusable-workflow:
  #   uses: ./.github/workflows/build-docker.yml
  #   with:
  #     image_name: my-app
  #     image_tag: ${{ inputs.environment }}-${{ github.sha }}
  #     file_path: ${{ vars.DOCKER_FILE_PATH }}
  #     # file_path: ./dev-riteshzode/Dockerfile
  #     environment: ${{ inputs.environment }}
  #   environment: ${{ inputs.environment }}

  call-reusable-workflow:
    uses: ./.github/workflows/build-docker.yml
    with:
      image_name: my-app
      image_tag: ${{ inputs.environment }}-${{ github.sha }}
      file_path: ${{ vars.DOCKER_FILE_PATH }}   # <--- This is correct!
      environment: ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
