name: workflow-2 run only when pull request is merge to main successfully

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    # - uses: actions/checkout@v4
    - name: build Dev part
      run: echo "build Dev part"
    - name: deploy Dev part
      run: echo "deploy Dev part"
      
  deploy-QA:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: QA
    steps:
    # - uses: actions/checkout@v4
    - name: build QA part
      run: echo "build QA part"
    - name: deploy QA part
      run: echo "deploy QA part"

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: deploy-QA
    if: success() 
          
  deploy-prod:
    runs-on: ubuntu-latest
    needs: manual-approval
    environment: Prod
    steps:
    # - uses: actions/checkout@v4
    - name: build Prod part
      run: echo "build Prod part"
    - name: deploy Prod part
      run: echo "deploy Prod part"
